config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  resources :zemis, only: [:index, :show, :new, :update, :edit, :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/zemi_controller.rb
class ZemiController < ApplicationController
  def index
    @zemi = zemi.all
  end

  def show
  end

  def new
  end

  def edit
  end
  
  def update
  end
  
  def destroy
  end
  

 private
 
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/zemi_helper.rb
module ZemiHelper
end

app/views/homes/top.html.erb
<h1>ようこそ"zemi名"へ</h1>
<p>本ホームページにはゼミ生の活動や活動方針などが記載されています。</p>
<%= link_to 'url', 'https://ja.wikipedia.org/wiki/Facebook'%> <!--ここは今後変更-->
<p>写真が5つほど横スクロールできる様にする</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Zemi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/zemi/edit.html.erb
<h1>投稿編集</h1>
<p>戻る</p>

app/views/zemi/index.html.erb
<h1>ゼミの投稿一覧</h1>

app/views/zemi/new.html.erb
<h1>新規投稿</h1>
<p>投稿日</p>
<p>内容</p>
<p>投稿する</p>

app/views/zemi/show.html.erb
<h1>投稿詳細</h1>
<p><%= link_to "戻る", zemi_path %></p>